#!/usr/bin/env pipenv run python
import click
from shoppinglist.main import Main

DEFAULT_PRICES_FILE='./prices/hue.yaml'

@click.command()
@click.argument('prices_file', type=click.Path(exists=True))
@click.argument('shopping_list_file', type=click.Path(exists=True))
def cli(prices_file, shopping_list_file):
    main = Main(prices_file, shopping_list_file)
    click.echo(main.process_file())


if __name__ == '__main__':
    cli()
